name: Render Matches Video 🆚
on:
  workflow_dispatch:
    inputs:
      round:
        description: "For which round ? (0 to 4)"
        required: true
        default: 0
jobs:
  render:
    name: 📹 Render Matches
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: pnpm i
      - run: echo $WORKFLOW_INPUT > input-props.json
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - run: pnpm build:matches
      - uses: actions/upload-artifact@v2
        with:
          name: matches.mp4
          path: out/matches.mp4
